### ISSUE TITLE
Bug: Strict TypeScript error with ESModules

### ISSUE THREAD

**Issue by dylanjha** [muxinc/elements#1008] opened 2024-10-30 16:27 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Other (add details below)

### Which operating systems are you using?

macOS

### Description

A simple react component like this:

```
import MuxPlayer from '@mux/mux-player-react';
const Foo = () => <MuxPlayer />;
```

Gives us the following TypeScript error with modern ESModules and a strict TypeScript config:

```
error TS2604: JSX element type 'MuxPlayer' does not have any construct or call signatures.

28       <MuxPlayer
          ~~~~~~~~~

src/components/custom/mediaPlayer/MediaPlayer.tsx:28:8 - error TS2786: 'MuxPlayer' cannot be used as a JSX component.
  Its type 'typeof import("/node_modules/@mux/mux-player-react/dist/types/index")' is not a valid JSX element type.

28       <MuxPlayer
          ~~~~~~~~~
```

### Steps to reproduce

Try reproducing this with a strict TS Config

### Current Behavior

Error building

### Expected Behavior

No error building

**Comment by luwes** [comment] 2024-10-30 17:07
@dylanjha what is the `moduleResolution`?

**Comment by rileytomasek** [comment] 2024-10-30 21:09
@luwes @dylanjha filed this for me. Here is the relevant `tsconfig.json`:
```json
{
  "compilerOptions": {
    "allowImportingTsExtensions": false,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "checkJs": true,
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": false,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["esnext", "dom", "dom.iterable"],
    "module": "NodeNext",
    "moduleDetection": "force",
    "moduleResolution": "NodeNext",
    "noEmit": true,
    "preserveWatchOutput": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es2022",
    "verbatimModuleSyntax": true
  }
}
```

**Comment by luwes** [comment] 2024-10-31 14:59
I tested the tsconfig above with a fresh Vite app and I can't reproduce it unfortunately.

Are you using a framework? 
Could you try restarting the TS server? sometimes that acts strangely when (re)installing node_modules.


![Image](https://github.com/user-attachments/assets/11826540-3910-49cf-947c-01de1afb6307)

**Comment by luwes** [comment] 2024-12-13 22:06
closing as I couldn't repro this

**Closed by luwes** 2024-12-13 22:06 UTC
