### ISSUE TITLE
Bug: Video is small and then expands, causing a "flash"

### ISSUE THREAD

**Issue by isaacg11** [muxinc/elements#611] opened 2023-03-15 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome, Safari, Firefox

### Which operating systems are you using?

macOS

### Description

Hello support,

When I try to load my video using mux-player-react, it shows a small version of the video until it's loaded then it shows it fullscreen . How do I prevent it flashing this small player? See attached video showing issue.

https://user-images.githubusercontent.com/13204510/225419201-e80e1c0c-ba75-4867-89b4-b16213ca237e.mov

Here's my code: https://gist.github.com/isaacg11/6123e205e602eebad4a3744bd72aec87

What I tried: I tried using the "placeholder" prop, but nothing is showing up when the video loads.

Please help!

### Reduced test case

https://gist.github.com/isaacg11/6123e205e602eebad4a3744bd72aec87

### Steps to reproduce

1. Open mux video fullscreen
2. See a small version of the player for a split second
3. See the player go fullscreen

### Current Behavior

Small player flashes before showing fullscreen

### Expected Behavior

Mux player should only show fullscreen

### Errors

no errors

### What version of the package are you using?

1.8.0

**Comment by luwes** [comment] 2023-03-16 01:03
thanks for the feedback @isaacg11

the Mux player behaves very much like the native HTML video element in relation to sizing so it will take the dimension of the actual loaded video data unless dimensions are set by you via CSS styles or the dimensions are restricted by the container.

in your example video it looks like a low resolution video segment is shown first (small) and then the player switches to the higher resolution.

the fix is very easy. add a style of `width: 100%; aspect-ratio: 9 / 16;` to the `MuxPlayer` and it should expand from the start.

**Comment by dylanjha** [comment] 2023-03-24 15:06
@isaacg11 

If you see this codesandbox that @luwes shared:

https://codesandbox.io/s/mux-player-react-portrait-7g1p5f?file=/src/App.js

This shows a portrait video similar to the one in your recording that is not having the resize issue that you experienced. From this example are you able to debug what is different compared to your application?

First off, the way to prevent the shift from happening is to apply CSS on the player element so that it takes up space explicitly without relying on the implicit size of the media. The player element by default has `width: 100%`, so the easiest way to explicitly apply sizing is to add an aspect-ratio. This works for the majority of use cases, but it will still depend on the markup and CSS surrounding the player, so depending on the styles around the player you might need some slight tweaks.

Thank you for the gist link, that's a good start, but it doesn't have enough code to demonstrate an isolated reproduction case. Can you either:

- Use codesandbox, replit, codepen, any of these tools to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
- Or provide a standalone public github repo that we can pull down to see the issue

Does that help @isaacg11 ? We'd love to help you get to the bottom of this one

**Comment by dylanjha** [comment] 2023-06-27 18:49
Closing as this is a CSS application issue

**Closed by dylanjha** 2023-06-27 18:49 UTC
Labels: good first issue, question
