### ISSUE TITLE
Example with svelte-kit not working

### ISSUE THREAD

**Issue by psntr** [muxinc/elements#541] opened 2023-01-12 08:33 UTC
First thank you for providing a Player with MUX. 

I'm trying to implement the player within sveltekit so naturally I checked the docs and exemples you provided. Nevertheless, after few attempts I decided to directly run locally your svelte-kit exemple. 

But just as for my attempts, I'm facing the same issue while using the player:
<img width="871" alt="Screenshot 2023-01-12 at 17 31 45" src="https://user-images.githubusercontent.com/20617539/212017001-5f710156-cc87-404d-a606-d084e17438e6.png">

Is it because I'm running it on localhost?

**Comment by dylanjha** [comment] 2023-01-12 22:45
Hi @psntr , thanks for opening

Running on localhost should work fine, it must be something else. Did you create your own sveltkit app, or did you clone this monorepo and find the one we have in examples/svelte-kit?

**Comment by psntr** [comment] 2023-01-13 05:52
Thank you @dylanjha for your reply. So I clone the repo and use the one in examples/svelte-kit. But indepently on the template, I also tried through the official docs and it results on the same error. 

I also suspect there is issue with the hls.js dependency, see below:

While there is an update on this issue, I'm using the hls.js as an temporary solution. But weirdly enough, at first I also encounter similar error with the latest issue "Uncaught TypeError: Cannot read properties of underfine (reading 'call')" and it seems to be known issue with the compiler. You can see here:
[hls.js](https://github.com/video-dev/hls.js/issues/5146)

**Comment by dev-justin** [comment] 2023-01-17 01:28
Same issue with the Vue example as well. Seems like the same issue.

**Comment by gkatsev** [comment] 2023-01-17 16:46
Are you'all cloning the repo? If so, you need to make sure you're using `yarn`, and you'd want to run `yarn` and `yarn build:packages` at the top level before you go into the examples and run a `yarn build` or a `yarn dev` in them.

**Comment by dylanjha** [comment] 2023-01-18 16:12
@psntr & @dev-justin thanks for reporting. 

Are either of you able to create a reproducible example in code sandbox that shows the error?

Here's a plain Svelte app that works, if this helps as a starting point: https://codesandbox.io/s/mux-player-svelte-u9nntl

Also, that specific error looks like it might have something to do with the underlying video. Can you try this playback-id and see if that works?: `FuJSYrK0014ec2LPnm11bzC2MAySAQPqA`. If that works then we can figure out what's wrong with your playback-id.

**Comment by dev-justin** [comment] 2023-01-18 17:47
@dylanjha here is an example that gets the errors I am experiencing (Vue 3 + Vite), used the same playback-id you mentioned. 

https://codesandbox.io/p/github/dev-justin/mux-player-test/draft/wonderful-water

**Comment by psntr** [comment] 2023-01-21 07:15
@dylanjha thanks for providing an example, but in your case your are using svelte, not the sveltekit framework. Using the framework, doesn't work. For some reasons I can't run the codesandbox (stuck on initiliazing). But feel free to clone the git repo I created with the Mux player and the error will occur once your `npm run dev`.

[repo](https://github.com/psntr/sveltekit-mux)

**Comment by dylanjha** [comment] 2023-01-23 17:26
Amazing, @psntr thank you for the repro case. We're a little busy this week with a company-wide offsite happening but the repro case helps a lot and we'll get back on this asap to help debug

**Comment by dylanjha** [comment] 2023-01-23 19:30
Digging it a bit, looks like @dev-justin is exactly right with that Hls.js issue being the root cause.

I'm not sure if upgrading our Hls.js dep will fix it (doesn't hurt to try though). It seems like the root cause is https://github.com/video-dev/hls.js/issues/5107, which isn't merged yet.

We'll go ahead and upgrade Hls.js here soon and (🤞🏼 maybe we get lucky), if that doesn't help then we'll work on trying to get that Hls.js issue pushed through or find another workaround

**Comment by dylanjha** [comment] 2023-01-24 04:53
@dev-justin @psntr 

This should be fixed on the latest canary build: https://www.npmjs.com/package/@mux/mux-player/v/1.6.0-canary.0-8747d00

Can you try pinning to that tag to see if it works for you?

**Comment by psntr** [comment] 2023-01-24 06:41
@dylanjha thanks for the follow up. I removed the package and re-install the version 1.6.0 but still got errors, you can see the console output:
<img width="1297" alt="Screenshot 2023-01-24 at 15 39 18" src="https://user-images.githubusercontent.com/20617539/214227602-0d11bc42-a5ed-46aa-a55f-34982526a86b.png">

**Comment by dylanjha** [comment] 2023-01-24 13:47
@psntr are you pinned to the canary release `1.6.0-canary.0-8747d00`?

I just tried it 😞 and looks like it's still a problem but slightly different now, I'm seeing the spinner loop indefinitely and the logs are a little different

<img width="1007" alt="call_2023-01-24_05-43-50" src="https://user-images.githubusercontent.com/764988/214310535-20f82659-20ed-4f7a-8e9a-0ccf1ddac0f4.png">

Looks like that upgrade fixed _something_, but not the core issue. We'll have to keep working on this

**Comment by stolinski** [comment] 2023-01-27 20:49
We're also seeing this, but it only recently popped up.

**Comment by dylanjha** [comment] 2023-02-01 16:56
We're working on getting a PR to Hls.js that will allow us to work-around this issue, stay tuned

**Comment by dylanjha** [comment] 2023-02-09 23:01
@psntr @stolinski we finally got a workaround in the latest canary tag: `1.7.1-canary.0-fdf34bb`

I tried it out in the reproduction case app that I had and the issue was resolved for me. This will go out in the next release!

**Comment by dylanjha** [comment] 2023-02-15 20:02
This should be fixed now in `1.8.0`. Please try and let us know!

**Closed** 2023-02-15 20:02 UTC
Labels: bug, enhancement, Status: Unconfirmed
