### ISSUE TITLE
Bug: mux-video-react MuxVideo thumbnail not properly displaying iOS

### ISSUE THREAD

**Issue by zachkaigler** [muxinc/elements#358] opened 2022-08-31 18:05 UTC
### Checklist

- [X] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [X] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-video

### Which browser(s) are you using?

- Safari on iOS

### Which operating system(s) are you using?

iOS

### How are you using Mux Elements?

`mux-video-react` npm package

### Describe the bug

`MuxVideo` component is not properly displaying the poster frame on iOS devices. It works fine on Chrome, Mac Safari, android, etc.

Link to code example:

https://56g2qf.csb.app/

Viewed on Chrome:
![Screen Shot 2022-08-31 at 2 02 32 PM](https://user-images.githubusercontent.com/77355552/187748044-24715d71-02c8-46df-8475-aabf99a63a96.png)

Viewed on iOS:
![Image from iOS](https://user-images.githubusercontent.com/77355552/187748526-3169989b-febd-489d-8cea-b85ea828b3ed.png)

Edit: Adding iPhone with the latest versions of iOS and safari + chrome-
![File](https://user-images.githubusercontent.com/77355552/187763872-2bf40c31-5529-4092-8872-f283b1a598b6.jpg)

## The current behavior
The poster frame does not display on iOS

## The expected behavior
The poster frame should display on iOS

**Comment by luwes** [comment] 2022-08-31 23:27
Closing here as it's not a bug I believe. See https://github.com/muxinc/elements/discussions/357#discussioncomment-3522267

**Closed by luwes** 2022-08-31 23:27 UTC
Labels: bug, enhancement, Status: Unconfirmed
