### ISSUE TITLE
poor Mux Player viewer experience

### ISSUE THREAD

**Issue by t-raven** [muxinc/elements#610] opened 2023-03-14 22:35 UTC
on march 9. we switched Videojs player to Mux Player

this resulted in dramaticly poorer viewer experience (see also startup time and playback success!)
![image](https://user-images.githubusercontent.com/3852013/225157103-5b3e710a-c8f6-476d-b4d7-2ed32f5430b0.png)

we have no negative (or positive, to be fair) feedback for the new player - except quite a bunch users who are not able to play video on Safari 13.1.2, however attached statistics are teryfying. why is that? :(

thanks

**Comment by luwes** [comment] 2023-03-15 01:49
thanks, very helpful. 

did you try different versions of Mux player? 
I believe we had 1 version `v1.7.0` that had a playback issue related to Safari.

**Comment by t-raven** [comment] 2023-03-15 11:08
we have `v1.7.1` on production, will update it to latest `1.8.0` and give it few days of observation, thanks for directions.

**Comment by t-raven** [comment] 2023-03-21 00:03
hi @luwes 
on 16. 3. we updated to `v.1.8.0`, sadly, it didn't help much :(

![image](https://user-images.githubusercontent.com/3852013/226490881-3d26520e-2327-4498-acae-76281540ebf6.png)

do you have any suggestion what might cause this, please?

**Comment by luwes** [comment] 2023-03-31 00:57
closing as this was caused by misreporting of errors caused by expired stream urls.

**Closed by luwes** 2023-03-31 00:57 UTC
