### ISSUE TITLE
[BUG] Mux player crushed in Nextjs 14.0.2

### ISSUE THREAD

**Issue by zrtsky** [muxinc/elements#818] opened 2023-11-10 09:04 UTC
### Discussed in https://github.com/muxinc/elements/discussions/817

<div type='discussions-op-text'>

<sup>Originally posted by **zrtsky** November 10, 2023</sup>
#### Screen
<img width="1035" alt="Screenshot 2023-11-10 at 10 53 32" src="https://github.com/muxinc/elements/assets/42916643/45ec05e3-3325-4c67-bd0c-9981cc14dd77">

#### Logs

<img width="638" alt="Screenshot 2023-11-10 at 10 56 38" src="https://github.com/muxinc/elements/assets/42916643/27827070-601a-487d-829e-6b5163ceeef9">

### PS

I think it's can be started from `next: 14.0.2-canary.0`, here is the [link](https://github.com/vercel/next.js/issues/57964#issuecomment-1791801804) to discussion about this issue
</div>

**Comment by Rychillie** [comment] 2023-11-13 03:11
same issue on [https://github.com/muxinc/next-video/issues/109](https://github.com/muxinc/next-video/issues/109)

**Comment by GabrielDucharme** [comment] 2023-11-13 15:26
Is there any way to fix this?

**Comment by luwes** [comment] 2023-11-13 16:14
Thanks for reporting! We're searching for the cause of this issue. We'll keep you updated here.

**Comment by KrustyC** [comment] 2023-11-13 16:51
I can confirm this also happen on my app since I upgraded next to 14.0.2. Had no issues on 14.0.1

**Comment by luwes** [comment] 2023-11-13 17:11
https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.0 still works
https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.1 fails

**Comment by KrustyC** [comment] 2023-11-20 10:41
Hello guys, is there any update on the progress of this?

**Comment by gusfune** [comment] 2023-11-20 10:42
For me it stopped since the release of Next 14.0.3

**Comment by mwawrusch** [comment] 2023-11-22 05:16
I am also having this problem with next.js 14.0.3 , turbo, typescript 5.3.2

**Comment by jamesvclements** [comment] 2023-11-29 23:37
@luwes Hey! Any update on this? Still seeing the issue on `v14.0.4-canary.26`, I'm keeping my project at `14.0.01` but would love to upgrade for the cache fixes in `14.0.4`.

**Comment by luwes** [comment] 2023-12-08 00:56
this is resolved in Next.js v14.0.4 https://github.com/vercel/next.js/releases/tag/v14.0.4

**Closed by luwes** 2023-12-08 00:56 UTC
