### ISSUE TITLE
Bug: mux-video and mux-video-react different behavior for classes 

### ISSUE THREAD

**Issue by iceiceart** [muxinc/elements#701] opened 2023-06-01 15:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video, mux-video-react

### Which browsers are you using?

Chrome, Safari

### Which operating systems are you using?

None

### Description

when I use `mux-video-react` and adding classes to the component like this
```
MuxVideo
                    className="class1 class2"
                  />
```

they applied to `<video>` tag
in html dom i see  `<video class="class1 class2">`

but when I use `mux-video` and add classes with classList props `el.classList.add("kw-full", "h-full");` they applied to the `<mux-video>` tag not to the `<video>`

it's very important to have possibility to add classes directly to `<video>` tag and I think that behavior should be the same for `mux-video-react` and `mux-video`  components?

Is any possibility to add classes directly to `<video>` tag by using `<mux-video>` component?

Thanks!

### Steps to reproduce

1. add classes to `mux-video-react` component check that classes applied to `<video>` tag
2. add classes to `mux-video` component check that classes applied to `<mux-video>` tag

### Current Behavior

1. add classes to `mux-video-react` component check that classes applied to `<video>` tag
2. add classes to `mux-video` component check that classes applied to `<mux-video>` tag

### Expected Behavior

classes should applied to `<video>` tag or should be the props to add classes directly to video tag

### What version of the package are you using?

0.15.2

**Comment by dylanjha** [comment] 2023-06-23 19:00
I see @iceiceart , thanks for opening this issue

The `<MuxVideo />` React component does not render a wrapper around the `<video>` tag, the top level element that gets returned in the render is the actual `<video>` tag itself, you can see here: https://github.com/muxinc/elements/blob/main/packages/mux-video-react/src/index.tsx#L70-L76

The `<mux-video>` HTML element works a little differently. It is a custom component itself, and it has a `<video>` tag in it's own shadow root.

Because of this, the two components work quite differently so the difference in behavior is expected.

---

> it's very important to have possibility to add classes directly to <video> tag
> Is any possibility to add classes directly to <video> tag by using <mux-video> component?

Can you elaborate on this please? I want to understand a little more of what you're trying to accomplish by adding classes to the video tag? Ideally anything you want to do should be possible with classes on the `<mux-video>` element.

**Comment by dylanjha** [comment] 2023-06-27 18:46
Going to close this because it is expected behavior, but we're happy to help find a work-around for your specific use case

**Closed by dylanjha** 2023-06-27 18:46 UTC
Labels: bug, Status: Unconfirmed
