### ISSUE TITLE
Bug: Not preventing device sleep

### ISSUE THREAD

**Issue by oburt** [muxinc/elements#313] opened 2022-07-27 23:54 UTC
### Checklist

- [X] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [X] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-player

### Which browser(s) are you using?

- Chrome
- Edge ("Edgeium")
- Safari
- Chrome Android

### Which operating system(s) are you using?

macOS, Windows, Android

### How are you using Mux Elements?

`<script>` tag

### Describe the bug

Whenever a video is playing, it should prevent the device from going to sleep. This should be the default behavior of most browsers with the default HTML video element, so I'm not sure what is changing in Mux Player that disables this. Based on my tests, Media Chrome does not have this problem, it is isolated to Mux Player. It doesn't happen on every device, but on those that it does, it happens consistently.

## Steps To Reproduce

1. Set device sleep or lock delay to something short for easier testing.
2. Start playing a Mux Player video and wait the amount of time for the sleep or lock to potentially activate.

Link to example: https://tmi.mux.com/sessions/opening-remarks (tested this behavior on Mux hosted videos to make sure it wasn't just on our website, it occurs on the TMI videos as well as in the Mux dashboard)

## The current behavior
Device falls asleep when video is playing

## The expected behavior
Device stays awake as long as video is playing

**Comment by dylanjha** [comment] 2022-07-28 15:58
Thanks for reporting @oburt -- we'll have a look

**Comment by luwes** [comment] 2022-07-28 18:57
Confirmed on an Android mobile device. My iPhone didn't have the issue.

was it on mobile devices only or on laptops as well?

**Comment by oburt** [comment] 2022-07-28 19:49
We had it reported on both Mac and Windows desktops, as well as Android phones.

**Comment by luwes** [comment] 2022-07-28 20:32
thanks, I can confirm on Chrome / Mac as well if I set "turn display off after" to a short time like 1min.

to me this looks like a browser bug because normally a playing video element should make the browser prevent the display from sleeping. it's possible it's related to that the Mux player `<video>` element is nested in the shadow dom.

**Comment by oburt** [comment] 2022-07-28 20:54
Yeah, my uneducated guess would also have been something about the video element existing in the shadow dom as well since it needs to be something fundamentally different in mux-video or mux-player to prevent that default HTML video behavior. I worked my way down the development stack and compared it to media-chrome on some of those browsers that had issues and media-chrome worked correctly.

An example <media-chrome>: https://media-chrome.mux.dev/examples/basic.html

**Comment by luwes** [comment] 2022-07-28 21:11
I filed a Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1348320

Confirmed it's not an issue on Safari and Firefox. 

On Edge it is an issue as well probably because the underlying Chromium.

**Comment by MrSethT** [comment] 2022-08-15 18:44
Here's the workaround I am using in the meantime for this.  (Sorry if this isn't how sharing of this should be done.  If there's a better place for it, point me to it.)

```
wakeLock = null;

startWakeLock = function () {
    document.addEventListener('visibilitychange', () => {
        if (wakeLock !== null && document.visibilityState === 'visible') {
            requestWakeLock();
        }
    })
    requestWakeLock();
};

requestWakeLock = async function () {
    // Create a reference for the Wake Lock.
    if (navigator.wakeLock) {// create an async function to request a wake lock
        try {
            wakeLock = await navigator.wakeLock.request('screen');
            console.log('requestWakeLock');
        } catch (err) {
            console.log(err.name);
        }
    }
};

releaseWakeLock = function () {
    if (wakeLock)
        wakeLock.release()
            .then(() => {
                console.log('releaseWakeLock');
                wakeLock = null;
            })
};

//get the mux-player
popupVideo = document.getElementById("vidPopup");
//add event listeners 
popupVideo.addEventListener("play", function () {
    startWakeLock();
});
popupVideo.addEventListener("pause", function () {
    releaseWakeLock();
});
```

**Comment by luwes** [comment] 2022-08-30 13:05
the fix is seemingly coming in Chrome 107 🎉 
https://bugs.chromium.org/p/chromium/issues/detail?id=1348320#c14

**Comment by gkatsev** [comment] 2022-08-30 16:31
According to the tags on the issue, it might even get ported down to 106!

**Comment by luwes** [comment] 2022-08-30 17:49
you're right woohoo `Labels: -Merge-Request-106 Hotlist-Merge-Approved Merge-Approved-106`

**Comment by oburt** [comment] 2022-08-31 17:39
Nice! Awesome that it got prioritized and turned around pretty quickly by the Chromium team

**Comment by luwes** [comment] 2022-10-03 23:27
this is fixed in Chrome 106 🎉 
thanks for reporting!

https://bugs.chromium.org/p/chromium/issues/detail?id=1348320#c19

**Closed by luwes** 2022-10-03 23:27 UTC
Labels: browser bug
