### ISSUE TITLE
Bug: Can't import the named export 'useEffect' from non EcmaScript  module

### ISSUE THREAD

**Issue by rockstar0711** [muxinc/elements#559] opened 2023-01-30 15:26 UTC
Thanks for this brilliant service. I have an issue and stuck here for around two days.
Here are description:

### Checklist

- [] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[mux-player-react]` or `yarn @mux/[mux-player-react]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
mux-player-react

### Which browser(s) are you using?
Chrome

### Which operating system(s) are you using?
Windows

### How are you using Mux Elements?
`import MuxPlayer from "@mux/mux-player-react";`

### Describe the bug
I wanna integrate mux react player to my react application. But got error like 
```
./node_modules/@mux/mux-player-react/dist/index.mjs
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
```
![image](https://user-images.githubusercontent.com/15241284/215517284-35b3ed7e-569d-421e-ba8f-fdce3d069eb5.png)
![image](https://user-images.githubusercontent.com/15241284/215517570-73577d58-429a-40f0-9a65-a9a2c02c2f7c.png)

## Steps To Reproduce

1. Remove all dependencies and re-install node module
2. Upgrade react version from 17 to 18
3. Remove package lock files and dependencies again and re-install and run the project.
Here is version of my dependencies.
```
"@mux/mux-player-react": "^1.6.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

Link to code example:
https://codesandbox.io/s/confident-phoebe-m3nuk0?file=/src/App.js

## The current behavior
Above issue occurs and not running the app. The weird thing is that it works well in codepen which I shared but it does not work on my end.

## The expected behavior
Play video without current issue so that I can integrate mux player to our react application.

**Comment by rockstar0711** [comment] 2023-01-31 01:05
Hello, I have tried on macOS but the same error occurs.
I am pretty sure, current code base have some issue. Would you mind investigate for about this bug report?
Thanks.

**Comment by dylanjha** [comment] 2023-01-31 18:43
Hi @rockstar0711 

This looks similar to #499 which is a React build issue.

> The weird thing is that it works well in codepen which I shared but it does not work on my end.

Since codepen/codesandbox are not able to repro the issue, can you set up a public github repo as a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? If you do that we can provide some more guidance around what might be going wrong in your React setup.

**Comment by rockstar0711** [comment] 2023-02-01 13:50
Hello, @dylanjha , I have checked #499 and also stackoverflow solutions.
and I updated the `react-script` v4 to 5 and got some another compile issues.
So I am sure this is related with react compile issue. not package issue. I might needed investigate about that.
![image](https://user-images.githubusercontent.com/15241284/216060628-1cbea870-f120-45ef-b59f-72ba53e6ea17.png)

**Comment by dylanjha** [comment] 2023-02-01 16:13
Is your app generated from create react app? We have a create react app example that we test builds against, but I've seen CRA have weird problems like this before.

If you can replicate in a new bare-bones repo I'd love to get to the bottom of it.

**Comment by dylanjha** [comment] 2023-02-01 17:15
Closing this as it's an issue specific to CRA or react-scripts, but please comment with more details or reproduction case so we can help you figure it out!

**Closed by dylanjha** 2023-02-01 17:15 UTC
Labels: bug, enhancement, Status: Unconfirmed
