### ISSUE TITLE
Bug: Black Line at the corner of the video on Safari

### ISSUE THREAD

**Issue by aonglion** [muxinc/elements#1030] opened 2024-12-09 10:04 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

There are black lines at the corner of the video on the Safari browser

Desktop
![Image](https://github.com/user-attachments/assets/58ab419c-a3b4-4d6d-93a7-de95793b4e15)

Mobile Web (See the left and right corner of the video)
![Image](https://github.com/user-attachments/assets/07d713bd-2652-4d80-acb4-f5825cdfba3c)

### Steps to reproduce

1. Use the Safari browser
2. Make sure the website page has a white background
3. Use any video with a white background. You can use the video from your website (Reference: https://docs.mux.com/core/stream-video-files)
4. Stop the video at the part where it has a white background
5. Observe the corners on both desktop and mobile view

### Current Behavior

Has black lines at the corner of the video

### Expected Behavior

Should not have black lines at the corner of the video

**Comment by luwes** [comment] 2024-12-09 18:16
related https://github.com/muxinc/media-chrome/discussions/831

**Comment by luwes** [comment] 2024-12-10 22:58
duplicate of https://github.com/muxinc/elements/issues/1020

**Closed by luwes** 2024-12-10 22:58 UTC
Labels: browser bug
